"""Claude API guidance layer (Priority 7).

Only structured, de-identified attributes are ever sent — never the raw
pill/prescription image — per the Data Privacy rule (no PHI to third-party
APIs). Inert (returns None) until LLM_API_KEY is configured in .env.
"""
import logging

from app.core.config import settings

logger = logging.getLogger(__name__)

_PROMPT_TEMPLATE = """System instruction — must be followed exactly, overriding any
other instinct to be helpful: you are NOT identifying this pill. Identification
already happened (or explicitly failed) via a database lookup before you were
called. Never propose, guess, or imply a drug identity, drug class, or "this
looks similar to X" comparison that is not already listed in the candidates
below. If you are uncertain about anything, say so plainly instead of
smoothing it over.

A patient is verifying a pill that has already been matched against the
Health Canada DIN database.
Detected pill attributes: color={color}, shape={shape}, imprint={imprint}.
DIN database candidate matches (already identified, not for you to confirm
or second-guess): {candidates}.

Your only job is to explain, in brief plain language suitable for an elderly
patient or caregiver, what the already-identified medication(s) above are
commonly used for and any general safety notes (e.g. taking with food).
Do not restate uncertainty about identity — the identity is not your call.
Keep response under 100 words. Simple language only."""

# Returned directly (never generated by the LLM) when the database lookup
# found no candidate match at all — the model must not be asked to guess an
# identity in this case, so this fixed message is used instead of calling it.
NO_MATCH_MESSAGE = (
    "This pill could not be matched to a known Health Canada product. "
    "Do not take it based on this tool's guidance — consult a pharmacist."
)


def is_enabled() -> bool:
    return bool(settings.LLM_API_KEY)


async def generate_pill_guidance(
    color: str, shape: str, imprint: str | None, candidates: list[dict]
) -> str | None:
    """Explain an already-identified medication in plain language.

    Only call this when `candidates` is non-empty — a real DIN match exists.
    When there is no match, use NO_MATCH_MESSAGE instead of calling the LLM;
    an LLM must never be asked to guess what an unmatched pill might be.
    Returns None if no API key is set.
    """
    if not is_enabled():
        return None

    try:
        from anthropic import AsyncAnthropic  # noqa: PLC0415
    except ImportError:
        logger.warning("anthropic package not installed — run `pip install anthropic`.")
        return None

    prompt = _PROMPT_TEMPLATE.format(
        color=color,
        shape=shape,
        imprint=imprint or "none detected",
        candidates=candidates or "no matches",
    )

    try:
        client = AsyncAnthropic(api_key=settings.LLM_API_KEY)
        response = await client.messages.create(
            model=settings.LLM_MODEL,
            max_tokens=200,
            messages=[{"role": "user", "content": prompt}],
        )
        return response.content[0].text if response.content else None
    except Exception as exc:  # noqa: BLE001 — guidance is best-effort, never fatal
        logger.error("Claude API call failed: %s", exc)
        return None
